file:
  upload-dir: src/main/resources/uploads

server:
  port: 8081

spring:
  application:
    name: cloudservice
  datasource:
    url: jdbc:sqlite:src/main/resources/database.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ru.netology.cloudservice.CustomSqliteDialect.SQLiteDialect
