file:
  upload-dir: src/main/resources/uploads

server:
  address: 0.0.0.0
  port: 8081

spring:
  application:
    name: cloudservice
  datasource:
    url: jdbc:postgresql://db:5432/cloudservice_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 200MB

logging:
  level:
    root: INFO
    ru.netology.cloudservice: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"