file:
  upload-dir: src/main/resources/uploads

server:
  address: localhost
  port: 8081

spring:
  application:
    name: cloudservice
  datasource:
    url: jdbc:sqlite:src/main/resources/database.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ru.netology.cloudservice.CustomSqliteDialect.SQLiteDialect
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 200MB

logging:
  level:
    root: INFO
    ru.netology.cloudservice: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"